  apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
  kind: Elasticsearch
  metadata:
    name: eck-test
    namespace: stream
  spec:
    version: 7.4.0
    nodes:
      - nodeCount: 3
        config:
          node.master: true
          node.data: true
          node.ingest: true
          reindex.remote.whitelist: live-jaeger1.inepex.net:9200
        podTemplate:
          metadata:
            labels:
              foo: bar
          spec:
            containers:
              - name: elasticsearch
                #env:
                    #- name: ES_JAVA_OPTS
                      #value: "-Xms1G -Xmx4G"
                resources:
                  requests: 
                    memory: 3Gi
                  limits:
                    memory: 6Gi
                    cpu: 4
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 300Gi
              storageClassName: local-storage # can be any available storage class
