apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nyomio-protocol
  name: nyomio-protocol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyomio-protocol
  template:
    metadata:
      labels:
        app: nyomio-protocol
    spec:
      containers:
        - name: nyomio-protocol
          image: streamprocessor_nyomio-protocol
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
          volumeMounts:
            - name: certsecret
              mountPath: /root/cert
              readOnly: true
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: grpcCertChainPath
              value: /root/cert/tls.crt
            - name: grpcPrivateKeyPath
              value: /root/cert/tls.pkcs8
      volumes:
        - name: certsecret
          secret:
            secretName: certsecret
