apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nyomio-protocol
  name: nyomio-protocol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyomio-protocol
  template:
    metadata:
      labels:
        app: nyomio-protocol
    spec:
      containers:
        - name: nyomio-protocol
          image: streamprocessor_nyomio-protocol
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
#          volumeMounts:
#            - name: ca-cert
#              mountPath: /root/cert
#              readOnly: true
          envFrom:
            - configMapRef:
                name: streamprocessor-config
#          env:
#            - name: elasticPassword
#              valueFrom:
#                  secretKeyRef:
#                      name: {{ .Values.global.elasticId }}es-elastic-user
#                      key: elastic
#          command: ["/bin/sh", "-c"]
#          args:
#            - keytool -import -noprompt -v -trustcacerts -file /root/cert/ca.pem -keystore /root/keystore_test.jks -keypass $(keyPass) -storepass $(storePasss); cd /root/nyomage-nyomio_protocol; bin/nyomage-nyomio_protocol;
#      volumes:
#        - name: ca-cert
#          secret:
#            secretName: {{ .Values.global.elasticId }}-ca
