apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nyomio-protocol-ingresstcp
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`nyomio-protocol-{{ .Release.Namespace }}.nyomio.local`)
      services:
        - name: nyomio-protocol
          port: 9500
  tls:
    passthrough: true
    secretName: certsecret
