apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.management.elasticsearch.hosts: ["${elasticHost}"]
    xpack.management.elasticsearch.username: elastic
    xpack.management.elasticsearch.password: ${elasticPassword}
  pipeline.conf: "
    input {\n
        tcp {\n
                port => 4560\n
                codec => json_lines\n
        }\n
}\n

output {\n
        elasticsearch {\n
                user => elastic\n
                password => \"${elasticPassword}\"\n
                hosts => [\"https://${elasticHost}:9200\"]\n
                cacert => \"/usr/share/logstash/cert/ca.crt\"\n
                index => \"flink_log-%{+YYYY.MM.dd}\"\n
        }\n
}\n"
