apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.5.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512M -Xmx512M"
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: {{ .Values.global.elasticId }}-es-elastic-user
                      key: elastic
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: pipeline.conf
            - name: ca-cert
              mountPath: /usr/share/logstash/cert
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
        - name: ca-cert
          secret:
            secretName: {{ .Values.global.elasticId }}-es-http-certs-public
      securityContext:
        fsGroup: 101
