apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: logstash-ingresstcp
spec:
  entryPoints:
    - logstash
  routes:
    - match: HostSNI(`*`)
      services:
        - name: logging-logstash
          port: 4560
