apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logging-logstash
spec:
  ports:
    - port: 4560
      targetPort: 4560
      name: logstash-api
  selector:
    app: logstash
