apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      initContainers:
      - name: keytool
        image: registry.k8s.inepex.net:444/javabox:openjdk-11
        command: ['sh', '-c', 'keytool -import -noprompt -v -trustcacerts -file /root/cert/ca.pem -keystore /opt/keystore/keystore_test.jks -keypass $(keyPass) -storepass $(storePasss);chown 9999:9999 /opt/keystore/keystore_test.jks;chmod 777 /opt/keystore/keystore_test.jks']
        volumeMounts:
          - name: keystore
            mountPath: /opt/keystore
          - name: ca-cert
            mountPath: /root/cert
            readOnly: true
        env:
          - name: keyPass
            value: ine123
          - name: storePasss
            value: ine123
        #securityContext:
            #privileged: true
      containers:
        - name: jobmanager
          image: registry.k8s.inepex.net:444/flink-logback:latest
          args:
            - jobmanager
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob
            - containerPort: 6125
              name: query
            - containerPort: 8081
              name: ui
          volumeMounts:
            - name: keystore
              mountPath: /opt/keystore
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
            - name: env.java.opts
              value: "-Xms1000M -Xmx1000M"
            - name: kafkaAddress
              value: bootstrap.stream.svc.cluster.local:9092
            - name: logstashAddress
              value: logging-logstash.stream.svc.cluster.local:4560
            - name: keyPass
              value: ine123
            - name: elasticSslKeystorePath
              value: /opt/keystore/keystore_test.jks
            - name: elasticSslKeystorePass
              value: ine123
            - name: elasticHost
              value: eck-test-es.stream.svc.cluster.local
            - name: elasticUser
              value: elastic
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: eck-test-elastic-user
                      key: elastic
            - name: deviceManagerUrl
              value: http://nyomage-api.stream.svc.cluster.local:8082
            - name: testCompanyApiUrl
              value: http://nyomage-api.stream.svc.cluster.local:8083
            - name: APP_ID
              value: flink-jobmanager
      volumes:
        - name: keystore
          emptyDir: {}
        - name: ca-cert
          secret:
            secretName: eck-test-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: stream
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      initContainers:
      - name: keytool
        image: registry.k8s.inepex.net:444/javabox:openjdk-11
        command: ['sh', '-c', 'keytool -import -noprompt -v -trustcacerts -file /root/cert/ca.pem -keystore /opt/keystore/keystore_test.jks -keypass $(keyPass) -storepass $(storePasss);chown 9999:9999 /opt/keystore/keystore_test.jks;chmod 777 /opt/keystore/keystore_test.jks']
        volumeMounts:
          - name: keystore
            mountPath: /opt/keystore
          - name: ca-cert
            mountPath: /root/cert
            readOnly: true
        env:
          - name: keyPass
            value: ine123
          - name: storePasss
            value: ine123
        securityContext:
            privileged: true
      containers:
        - name: taskmanager
          image: registry.k8s.inepex.net:444/flink-logback:latest
          args:
            - taskmanager
          ports:
            - containerPort: 6121
              name: data
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query
          volumeMounts:
            - name: keystore
              mountPath: /opt/keystore
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
            - name: env.java.opts
              value: "-Xms1000M -Xmx1000M"
            - name: kafkaAddress
              value: bootstrap.stream.svc.cluster.local:9092
            - name: logstashAddress
              value: logging-logstash.stream.svc.cluster.local:4560
            - name: keyPass
              value: ine123
            - name: elasticSslKeystorePath
              value: /opt/keystore/keystore_test.jks
            - name: elasticSslKeystorePass
              value: ine123
            - name: elasticHost
              value: eck-test-es.stream.svc.cluster.local
            - name: elasticUser
              value: elastic
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: eck-test-elastic-user
                      key: elastic
            - name: deviceManagerUrl
              value: http://nyomage-api.stream.svc.cluster.local:8082
            - name: testCompanyApiUrl
              value: http://nyomage-api.stream.svc.cluster.local:8083
            - name: APP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: keystore
          emptyDir: {}
        - name: ca-cert
          secret:
            secretName: eck-test-ca
