package com.inepex.nyomagestreamprocessor.trippipeline.maptotrip

object Constants {

    const val CONTINOUS_LOCATION_EXTREME_SMALL_DISTANCE_METERS = 100
    const val CONTINOUS_LOCATION_EXTREME_SMALL_INTERVAL_SECONDS = 10
    const val CONTINOUS_LOCATION_SPEED_THRESHOLD_METERPERSEC = 100
    const val CONTINOUS_LOCATION_DISTANCE_THRESHOLD_METERS = 5000
    const val CONTINOUS_LOCATION_INTERVAL_THRESHOLD_SECONDS = 300
    const val MOVEMENT_MINIMAL_INTERVAL_SECONDS = 60
    const val MOVEMENT_SPEED_THRESHOLD_METERPERSEC = 0.3
    const val MOVEMENT_JOIN_MAX_DISTANCE_METERS = 100
//    const val TIME_JUMP_THRESHOLD_SECONDS = 300.0
    const val WAIT_MIN_INTERVAL_SECONDS = 120



}
