apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: {{ if .Values.global.dev }} 1 {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: flink-taskmanager
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      containers:
        - name: taskmanager
#          image: registry.k8s.inepex.net:444/flink-logback:latest
          image: flink-logback
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
          args:
            - taskmanager
          ports:
            - containerPort: 6121
              name: data
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query
          volumeMounts:
            - name: certsecret
              mountPath: /root/cert
              readOnly: true
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: keystorePath
              value: /root/cert/java_keystore.jks
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
#            - name: env.java.opts
#              value: "-Xms1000M -Xmx1000M"
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: {{ .Values.global.elasticId }}-es-elastic-user
                      key: elastic
      volumes:
        - name: certsecret
          secret:
            secretName: certsecret

