apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: {{ if .Values.global.dev }} 1 {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: flink-taskmanager
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      initContainers:
      - name: keytool
#        image: registry.k8s.inepex.net:444/javabox:openjdk-11
        image: openjdk:11
        command: [
          'sh', '-c',
          'keytool -import -noprompt -v -trustcacerts -file /root/cert/ca.crt
           -keystore /opt/keystore/keystore_test.jks -keypass $(keyPass)
           -storepass $(storePasss);chown 9999:9999 /opt/keystore/keystore_test.jks;chmod 777
           /opt/keystore/keystore_test.jks'
        ]
        volumeMounts:
          - name: keystore
            mountPath: /opt/keystore
          - name: ca-cert
            mountPath: /root/cert
            readOnly: true
        envFrom:
          - configMapRef:
              name: streamprocessor-config
        securityContext:
            privileged: true
      containers:
        - name: taskmanager
#          image: registry.k8s.inepex.net:444/flink-logback:latest
          image: flink-logback
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
          args:
            - taskmanager
          ports:
            - containerPort: 6121
              name: data
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query
          volumeMounts:
            - name: keystore
              mountPath: /opt/keystore
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
#            - name: env.java.opts
#              value: "-Xms1000M -Xmx1000M"
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: {{ .Values.global.elasticId }}-es-elastic-user
                      key: elastic
#            - name: APP_ID
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
      volumes:
        - name: keystore
          emptyDir: {}
        - name: ca-cert
          secret:
            secretName: {{ .Values.global.elasticId }}-es-http-certs-public
