apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy-devicemanagerapi-impl
  name: dummy-devicemanagerapi-impl
spec:
  selector:
    app: dummy-devicemanagerapi-impl
  ports:
    - port: 8080
      targetPort: 8080
