{{ if .Values.global.dev }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kafka-outside-0-ingresstcp
spec:
  entryPoints:
    - kafka
  routes:
    - match: HostSNI(`*`)
      services:
        - name: outside-0
          port: 32400
{{ end }}
