global:
  dev: true
  elasticId: eck
  # can be "docker", "minikube", "server"
  clusterType: docker
  flinkEnabled: true
  deviceManagerUrl: https://dummy-devicemangerapi-impl-default.nyomio.local



