apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyomio-nyom-stream-processor-flink-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: flink-pipeline-dev
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: flink-pipeline-dev
      annotations:
    spec:
      containers:
        - name: "flink-pipeline"
          image: "nyomio-nyom-stream-processor-flink-pipeline-skaffold"
          imagePullPolicy: Never
          ports:
            - name: ui
              containerPort: 8081
            - name: debug
              containerPort: 5005
          volumeMounts:
            - name: certsecret
              mountPath: /opt/flink/cert
              readOnly: true
          env:
            - name: SKAFFOLD
              value: "1"
            - name: JAVA_TOOL_OPTIONS
              value: -Xms256m -Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
            - name: keystorePath
              value: /opt/flink/cert/java_keystore.jks
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: elasticPassword
              valueFrom:
                secretKeyRef:
                  name: eck-es-elastic-user
                  key: elastic
          envFrom:
            - configMapRef:
                name: streamprocessor-config
      volumes:
        - name: certsecret
          secret:
            secretName: certsecret
