apiVersion: v1
kind: ConfigMap
metadata:
  name: streamprocessor-config
data:
  kafkaAddress: bootstrap.{{ .Release.Namespace }}.svc.cluster.local:9092
  logstashAddress: logging-logstash.{{ .Release.Namespace }}.svc.cluster.local:4560
  keystorePass: developer
  elasticHost: {{ .Values.global.elasticId }}-es-http.{{ .Release.Namespace }}.svc.cluster.local
  elasticPort: "9200"
  elasticUser: elastic
  deviceManagerUrl: {{ .Values.global.deviceManagerUrl }}
#              valueFrom:
#                  secretKeyRef:
#                      name: eck-test-elastic-user
#                      key: elastic
