apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy-companyapi-impl
  name: {{ .Release.Name }}-companyapi-impl
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dummy-companyapi-impl
  ports:
    - port: 9500
      targetPort: 9500
