apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-jobmanager
  template:
    metadata:
      labels:
        app: flink-jobmanager
    spec:
      containers:
        - name: jobmanager
          image: streamprocessor_flink-pipeline
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
          command: ["/bin/bash", "-c"]
          args:
            - >
              /docker-entrypoint.sh job-cluster
              -Djobmanager.rpc.address=flink-jobmanager
              -Dparallelism.default=2
              -Dblob.server.port=6124
              -Dqueryable-state.server.ports=6125
              --job-id 00000000000000000000000000000001
              $(/opt/flink/conf/latest_checkpoint_path.sh)
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob
            - containerPort: 6125
              name: query
            - containerPort: 8081
              name: ui
          volumeMounts:
            - name: config-volume
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml
            - name: config-volume
              mountPath: /opt/flink/conf/latest_checkpoint_path.sh
              subPath: latest_checkpoint_path.sh
            - name: certsecret
              mountPath: /opt/flink/cert
              readOnly: true
            - name: shared-volume
              mountPath: /opt/flink/data
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: keystorePath
              value: /opt/flink/cert/java_keystore.jks
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
            - name: elasticPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.elasticId }}-es-elastic-user
                  key: elastic
      volumes:
        - name: config-volume
          configMap:
            name: flink-config
            defaultMode: 0777
        - name: certsecret
          secret:
            secretName: certsecret
        - name: shared-volume
          persistentVolumeClaim:
            claimName: flink-shared-pvc

