apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: {{ if .Values.global.dev }}2{{ else }}2{{ end }}
  selector:
    matchLabels:
      app: flink-taskmanager
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      containers:
        - name: taskmanager
          image: streamprocessor_flink-pipeline
          imagePullPolicy: {{ if .Values.global.dev }}Never{{ else }}IfNotPresent{{ end }}
          args: ["task-manager", "-Djobmanager.rpc.address=flink-jobmanager"]
          volumeMounts:
            - name: config-volume
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml
            - name: certsecret
              mountPath: /opt/flink/cert
              readOnly: true
            - name: shared-volume
              mountPath: /opt/flink/data
          envFrom:
            - configMapRef:
                name: streamprocessor-config
          env:
            - name: keystorePath
              value: /opt/flink/cert/java_keystore.jks
            - name: elasticPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.elasticId }}-es-elastic-user
                  key: elastic
      volumes:
        - name: config-volume
          configMap:
            name: flink-config
        - name: certsecret
          secret:
            secretName: certsecret
        - name: shared-volume
          persistentVolumeClaim:
            claimName: flink-shared-pvc

