apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: stream
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.management.elasticsearch.hosts: ["https://eck-test-es.stream.svc.cluster.local:9200"]
    xpack.management.elasticsearch.username: elastic
    xpack.management.elasticsearch.password: ${elasticPassword}
  pipeline.conf: "
    input {\n
        tcp {\n
                port => 4560\n
                codec => json_lines\n
        }\n
}\n

output {\n
        elasticsearch {\n
                user => elastic\n
                password => \"${elasticPassword}\"\n
                hosts => [\"https://eck-test-es.stream.svc.cluster.local:9200\"]\n
                cacert => \"/usr/share/logstash/ca.pem/ca.pem\"\n
                index => \"flink_log-%{+YYYY.MM.dd}\"\n
        }\n
}\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-logstash
  namespace: stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: logging
        k8s-app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.1.1
          imagePullPolicy: Always
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512M -Xmx512M"
            - name: elasticPassword
              valueFrom:
                  secretKeyRef:
                      name: eck-test-elastic-user
                      key: elastic
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: pipeline.conf
            - name: ca-cert
              mountPath: /usr/share/logstash/ca.pem
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
        - name: ca-cert
          secret:
            secretName: eck-test-ca
      securityContext:
        fsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: logging
    kubernetes.io/name: logstash
  name: logging-logstash
  namespace: stream
spec:
  ports:
    - port: 4560
      targetPort: 4560
      name: logstash-api
  selector:
    k8s-app: logstash
