apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: {{ .Values.global.elasticId }}
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: {{ if .Values.global.dev }}-Xms512M -Xmx512M{{ else }}-Xms2G -Xmx2G{{ end }}
          resources:
            requests:
              memory: {{ if .Values.global.dev }}1Gi{{ else }}4Gi{{ end }}
            limits:
              memory: {{ if .Values.global.dev }}1Gi{{ else }}4Gi{{ end }}
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500M
          storeageClassName: standard
  http:
    tls:
      certificate:
        secretName: certsecret
