apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: elasticsearch-ingsresstcp
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`elasticsearch-{{ .Release.Namespace }}.nyomio.local`)
      services:
        - name: {{ .Values.global.elasticId }}-es-http
          port: 9200
  tls:
    passthrough: true
    secretName: certsecret
