apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: {{ .Values.global.elasticId }}
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: {{ if .Values.global.dev }}1{{ else }}3{{ end }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: {{ if .Values.global.dev }}-Xms384M -Xmx384M{{ else }}-Xms2G -Xmx2G{{ end }}
          resources:
            limits: {}
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ if .Values.global.dev }}500M{{ else }}100Gi{{ end }}
          storeageClassName: {{ if .Values.global.dev }}standard{{ else }}longhorn{{ end }}
  http:
    tls:
      certificate:
        secretName: certsecret
