apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: eck-test
  namespace: {{ .Values.global.namespace }}
spec:
  version: 7.4.0
  nodes:
    - nodeCount: {{ if .Values.global.dev }}1{{ else }}3{{ end }}
      config:
        node.master: true
        node.data: true
        node.ingest: true
        reindex.remote.whitelist: live-jaeger1.inepex.net:9200
      podTemplate:
        metadata:
          labels:
            foo: bar
        spec:
          containers:
            - name: elasticsearch
#              resources:
#                requests:
#                  memory: 3Gi
#                limits:
#                  memory: 6Gi
#                  cpu: 4
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500M
            storeageClassName: standard
#                storage: 300Gi
#            storageClassName: local-storage # can be any available storage class
