apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ .Values.global.namespace }}
spec:
  version: 7.4.0
  nodeCount: 1
  elasticsearchRef:
    name: eck-test
