apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kibana-ingresstcp
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`kibana-{{ .Release.Namespace }}.nyomio.local`)
      services:
        - name: {{ .Values.global.elasticId }}-kb-http
          port: 5601
  tls:
    passthrough: true
    secretName: certsecret
