- op: replace
  path: /spec/replicas
  value: 3
- op: remove
  path: /spec/template/spec/affinity
- op: remove
  path: /spec/template/spec/containers/0/resources
#- op: replace
  #path: /spec/template/spec/containers/0/resources/requests/memory
  #value: 400Mi
#- op: replace
  #path: /spec/template/spec/containers/0/resources/requests/cpu
  #value: 1 
- op: replace
  path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
  value: 300M
- op: replace
  path: /spec/volumeClaimTemplates/0/spec/storageClassName
  value: standard
